
@baseUrl = http://localhost:5000/api/auth
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYmIzY2U1LTVkMmItNGUwNS04YmMyLTUyZGY1YmEzZmFkZCIsInN0dWRlbnRSZWdObyI6IlNDL0NPTS8wMDA4LzIyIiwiZnVsbE5hbWUiOiJTQy9DT00vMDAwOC8yMiIsInJvbGUiOiJhZG1pbiIsInllYXJPZlN0dWR5IjoiMSIsImlhdCI6MTc3MTIyNzgxNCwiZXhwIjoxNzcxMzE0MjE0fQ.uahSr1cnSD5xnp1SMjCB-jh8CBRpz_0AY87WOG-oAOk

@studentToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc2MGFlM2NjLWYxZTEtNDRlNC05OTUxLTE3NWFkNWY5ZmIxYSIsInN0dWRlbnRSZWdObyI6IlNDL0NPTS8wMDA4LzI2IiwiZnVsbE5hbWUiOiJTQy9DT00vMDAwOC8yNiIsInJvbGUiOiJtZW1iZXIiLCJ5ZWFyT2ZTdHVkeSI6IjEiLCJlbWFpbCI6ImJyYXlvZ2FrZW55ZTA0QGdtYWlsLmNvbSIsImlhdCI6MTc3MTIzMzk0MywiZXhwIjoxNzcxMzIwMzQzfQ.J_ZUE_X0ZzxyzsQlOawxBt-KPTObMtPzfxed0ezNCCE
@regNo = SC/COM/0008/22
@email = codewithgakenye@gmail.com

@StudentregNo = SC/COM/0008/26
@Studentemail = brayogakenye04@gmail.com

### 1. Register a new admin
# If password is omitted, it defaults to the studentRegNo
POST {{baseUrl}}/register
Content-Type: application/json

{
  "studentRegNo": "{{regNo}}",
  "email": "{{email}}",
  "role": "admin"
}

## 1. Register a new student
# If password is omitted, it defaults to the studentRegNo
###
POST {{baseUrl}}/register
Content-Type: application/json

{
  "studentRegNo": "{{StudentregNo}}",
  "email": "{{Studentemail}}",
  "role": "member"
}

### 2. Login
# This will return a token and 'requireProfileCompletion' status

POST {{baseUrl}}/login
Content-Type: application/json

{
  "studentRegNo": "{{StudentregNo}}",
  "password": "{{StudentregNo}}"
}

### 3. Forgot Password
# This triggers the professional email with the Reset Button
POST {{baseUrl}}/forgot-password
Content-Type: application/json

{
  "studentRegNo": "{{regNo}}",
  "email": "{{email}}"
}

### 4. Reset Password
# 'token' comes from the email link query parameter (?token=...)
POST {{baseUrl}}/reset-password
Content-Type: application/json

{
  "token": "PASTE_TOKEN_FROM_EMAIL_HERE",
  "newPassword": "NewSecurePassword456"
}

### --------------------------------------------------------------
### Protected Routes (Requires @token to be set above)
### --------------------------------------------------------------

### 5. Complete Profile
# Used after first login to update full details
PUT {{baseUrl}}/complete-profile
Authorization: Bearer {{studentToken}}
Content-Type: application/json

{
  "studentRegNo": "{{StudentregNo}}",
  "fullName": "John1 Doe",
  "yearOfStudy": "3",
  "email": "{{Studentemail}}",
  "role":"admin"
}

### 6. Update Password (Authenticated)
# Changes password for the currently logged-in user
PUT {{baseUrl}}/update-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "password": "AnotherNewPassword789"
}

### 7. Get User by Registration Number
GET {{baseUrl}}/user/by-reg-no?studentRegNo={{regNo}}
Authorization: Bearer {{token}}